version: '3.8'

services:
  aiproxy:
    build: .
    container_name: go-aiproxy
    ports:
      - "3000:3000"
    environment:
      - AIPROXY_HOST=0.0.0.0
      - AIPROXY_PORT=3000
      - AIPROXY_API_KEY=${API_KEY:-123456}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aiproxy-network

networks:
  aiproxy-network:
    driver: bridge